<<<<<<< HEAD
services:
    database:
        build:
            context: database
            dockerfile: Dockerfile
        container_name: database
        image:  crypto-tracker
        volumes:
            - db_data:/data
            - ./database/sample.sql:/data/sample.sql
        command: ["tail", "-f", "/dev/null"]
        
volumes:
    db_data:
=======
services:
    database:
        build:
            context: database
            dockerfile: Dockerfile
        container_name: database
        image:  crypto-tracker
        volumes:
            - db_data:/data
            - ./database/sample.sql:/data/sample.sql
        command: ["tail", "-f", "/dev/null"]
        
volumes:
    db_data:
>>>>>>> 6daa86c (Add project setup)
